server:
  servlet:
    context-path: /api
  tomcat:
    max-http-form-post-size: 20MB
  port: ${PRODUCER_PORT:8081}

spring:
  application:
    name: penelope-api-rest

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}
    # Força a confirmação de que a mensagem foi entregue (Publisher Confirms)
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: auto
        # Tenta reprocessar a mensagem até 3 vezes antes de jogar para a DLQ
        concurrency: 3
        max-concurrency: 10
        retry:
          enabled: true
          initial-interval: 2000ms
          max-attempts: 3
          multiplier: 2.0
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    docExpansion: none
    operationsSorter: method
  api-docs:
    enabled: true
    path: /api-docs

app:
  update:
    dir: uploads
  frontend:
    url: http://localhost:3000
  security:
    token:
      secret: ${JWT_API_KEY}
  cors:
    allowed-origins:
      - "http://localhost:8081" # Back
      - "http://localhost:3000" # dev
      - "http://localhost:3001" # homol
      - "http://localhost:3002" # prod

auth-service:
  api:
    base-url: ${AUTH_SERVICE_BASE_URL:http://localhost:9000/api}

calcom:
  api:
    base-url: https://api.cal.com
    key: ${CALCOM_API_KEY}
    version-v1: 2024-06-14
    version-v2: 2024-08-13
  webhook:
    secret: ${CALCOM_WEBHOOK_SECRET}
rabbitmq:
  exchanges:
    estate: ${RABBITMQ_EXCHANGE_ESTATE:estate.exchange}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}