version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: penelope-rabbitmq
    restart: unless-stopped
    ports:
      - "${RABBITMQ_PORT}:5672"     # Porta TCP para o Spring Boot (Producer e Consumer)
      - "${RABBITMQ_UI_PORT}:15672" # Porta HTTP para você acessar o painel no Chrome
    environment:

      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      # Cria um volume persistente. Se você desligar o Docker, não perde as filas.
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
    name: penelope_rabbitmq_data